### ISSUE TITLE
k8s-dns-* 版本

### ISSUE THREAD

**Issue by arhool** [cocowool/k8s-go#3]
k8s-dns-sidecar-amd64:1.14.9 k8s-dns-kube-dns-amd64:1.14.9
k8s-dns-dnsmasq-nanny-amd64:1.14.9

阿里云镜像库没有1.14.9版本的吧，我在上面找到的只有1.14.8的
当然我已经参照文档安装成功，谢谢

**Comment by cocowool** [comment]
close the issue.
